//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hangman.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2
        ///1080
        ///&amp;c
        ///10-point
        ///10th
        ///11-point
        ///12-point
        ///16-point
        ///18-point
        ///1st
        ///2,4,5-t
        ///2,4-d
        ///20-point
        ///2D
        ///2nd
        ///30-30
        ///3D
        ///3-D
        ///3M
        ///3rd
        ///48-point
        ///4-D
        ///4GL
        ///4H
        ///4th
        ///5-point
        ///5-T
        ///5th
        ///6-point
        ///6th
        ///7-point
        ///7th
        ///8-point
        ///8th
        ///9-point
        ///9th
        ///a
        ///a&apos;
        ///a-
        ///A&amp;M
        ///A&amp;P
        ///A.
        ///A.A.A.
        ///A.B.
        ///A.B.A.
        ///A.C.
        ///A.D.
        ///A.D.C.
        ///A.F.
        ///A.F.A.M.
        ///A.G.
        ///A.H.
        ///A.I.
        ///A.I.A.
        ///A.I.D.
        ///A.L.
        ///A.L.P.
        ///A.M.
        ///A.M.A.
        ///A.M.D.G.
        ///A.N.
        ///a.p.
        ///a.r.
        ///A.R.C.S.
        ///A.U.
        ///A.U.C.
        ///A.V.
        ///a.w.
        ///A.W.O.L.
        ///A/C
        ///A/F
        ///A/O
        ///A/P
        ///A/V
        ///A1
        ///A-1
        ///A4
        ///A5
        ///AA
        ///AAA
        ///AAAA
        ///AAAAAA
        ///AAAL
        ///AAAS
        ///Aaberg
        ///Aachen
        ///AAE
        ///AAEE
        ///AAF
        ///AAG
        ///aah
        ///aahed
        ///aahing
        ///aahs
        ///AAII
        ///aal
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_wordlist {
            get {
                return ResourceManager.GetString("en_wordlist", resourceCulture);
            }
        }
    }
}
